import { GroupBox, HorizontalBox, Palette, StandardTableView, TabWidget, VerticalBox } from "std-widgets.slint";

export global MainWindowProperties {
    in property <string> about;
    in property <length> font_size;
    in property <[[StandardListViewItem]]> stream_properties: [];
}

export component MainWindow inherits Window {
    preferred-width: 1200px;
    preferred-height: 900px;
    min-width: 640px;
    min-height: 480px;
    title: @tr("Better Media Info");
    icon: @image-url("logo_96x96.png");
    default-font-family: "Arial";
    default-font-size: MainWindowProperties.font_size;
    init => {
        Palette.color-scheme = ColorScheme.light;
    }
    VerticalLayout {
        TabWidget {
            Tab {
                title: @tr("About");
                VerticalBox {
                    GroupBox {
                        title: @tr("Version");
                        vertical-stretch: 0;
                        Text {
                            text: MainWindowProperties.about;
                            color: Palette.control-foreground;
                        }
                    }

                    GroupBox {
                        title: @tr("Properties");
                        vertical-stretch: 1;
                        StandardTableView {
                            columns: [
                                { title: @tr("Stream") },
                                { title: @tr("Property") },
                            ];
                            rows: MainWindowProperties.stream_properties;
                        }
                    }
                }
            }
        }
    }
}
